{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.1.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.1.1.jar",
          "url": "builder-8.1.1.jar",
          "size": 11849525,
          "sha512": "fbd281671ac9efd097b72dbf5f1981135015f848ed84bac3e34f9765f2d5075491502f8871f82f507cb191f4622a8ffb0461bf66b2d709d6e36861aff0c38699",
          "sha256": "70fab2771ce774022fc5419b82d48d4c9a0309fc727cc6aad4e57ae164f78de8",
          "sha1": "5594d3763845845e708896806fdc639a145f47c9",
          "md5": "d2377b6c0af6833ef8a9420fee41add6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.1.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.1.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.1.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.1.1"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.1.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.1.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.20-RC2"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.1.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.1.1.jar",
          "url": "builder-8.1.1.jar",
          "size": 11849525,
          "sha512": "fbd281671ac9efd097b72dbf5f1981135015f848ed84bac3e34f9765f2d5075491502f8871f82f507cb191f4622a8ffb0461bf66b2d709d6e36861aff0c38699",
          "sha256": "70fab2771ce774022fc5419b82d48d4c9a0309fc727cc6aad4e57ae164f78de8",
          "sha1": "5594d3763845845e708896806fdc639a145f47c9",
          "md5": "d2377b6c0af6833ef8a9420fee41add6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.1.1-javadoc.jar",
          "url": "builder-8.1.1-javadoc.jar",
          "size": 400630,
          "sha512": "ad024313199edc3e706db3569ec7057da326d6a2d6ae77e24c61964a8954e8fcd86df080aa4fd7196bc910e02b596e492de4d965d15536d74f927657a8829e4d",
          "sha256": "e9639392b13eade323592f1398a096f05470064cc473073b9988336d8d5a6b16",
          "sha1": "084da213b1dd6647cdad7665da0144847bc3cc5b",
          "md5": "81fb0d524c958b26cad1bb9595e4889a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.1.1-sources.jar",
          "url": "builder-8.1.1-sources.jar",
          "size": 281982,
          "sha512": "5bc029e128d4f5b171192964cd62d8605a8e63b8ab74afc1fcdb0c5356dfd2002ca21a061c844804b4f3f21b45b21c27fb684e93b2c37d276e6cb3b31cfed7ec",
          "sha256": "ba8981799ba6833f1e19424cd607d2916eb74830c617f23fbaec603d13ccbdd8",
          "sha1": "c8999eb124da1c4d67fddac1e3a4e89e98db8a3e",
          "md5": "6b0bcaca1170db663f169ceb121c01f1"
        },
        {
          "name": "builder-8.1.1-sources.jar",
          "url": "builder-8.1.1-sources.jar",
          "size": 281982,
          "sha512": "5bc029e128d4f5b171192964cd62d8605a8e63b8ab74afc1fcdb0c5356dfd2002ca21a061c844804b4f3f21b45b21c27fb684e93b2c37d276e6cb3b31cfed7ec",
          "sha256": "ba8981799ba6833f1e19424cd607d2916eb74830c617f23fbaec603d13ccbdd8",
          "sha1": "c8999eb124da1c4d67fddac1e3a4e89e98db8a3e",
          "md5": "6b0bcaca1170db663f169ceb121c01f1"
        }
      ]
    }
  ]
}
