{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.profileinstaller",
    "module": "profileinstaller",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "profileinstaller-1.3.0.aar",
          "url": "profileinstaller-1.3.0.aar",
          "size": 47529,
          "sha512": "8f1f5298006e638acfe2409d7068507b3a29d2b2be8144d7753f6c54dac0b0a90115757ecbffb9293ef79c5665c786cacde853fd5b1d442e5e7fb76ed440d995",
          "sha256": "34e8b2bfc74e23c1525e3da903ae449b7f1b440aef45e18159ee470e91997f48",
          "sha1": "624641814089cd7bebf427aafa68ac089fb38261",
          "md5": "9e2082ba4d37f8a2b3817dcc97b69793"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "profileinstaller-1.3.0.aar",
          "url": "profileinstaller-1.3.0.aar",
          "size": 47529,
          "sha512": "8f1f5298006e638acfe2409d7068507b3a29d2b2be8144d7753f6c54dac0b0a90115757ecbffb9293ef79c5665c786cacde853fd5b1d442e5e7fb76ed440d995",
          "sha256": "34e8b2bfc74e23c1525e3da903ae449b7f1b440aef45e18159ee470e91997f48",
          "sha1": "624641814089cd7bebf427aafa68ac089fb38261",
          "md5": "9e2082ba4d37f8a2b3817dcc97b69793"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "profileinstaller-1.3.0-sources.jar",
          "url": "profileinstaller-1.3.0-sources.jar",
          "size": 38647,
          "sha512": "19daf008ce2e01e54e65e5c1ed61be3873b5c3b150d668da72a96c36e7c6736ee4be42319986c78a72dec67ec32194cf5131e5e8123b7de9ac10b81a786524e6",
          "sha256": "1d53d3dd1665143812f7fab691ca25f2f65d6c4daf7b6e607945b8f601d6244c",
          "sha1": "14f0bfd648db85e84b8792599b5ab1ff2c67df7f",
          "md5": "64c3c0de78185b699d574daa8590914b"
        }
      ]
    }
  ]
}