{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-rx3",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "dhafiarkonhbfll4adozkt6cc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-rx3-1.5.0.jar",
          "url": "kotlinx-coroutines-rx3-1.5.0.jar",
          "size": 70612,
          "sha512": "8bf6118be85cb8a4058e59ca1b4a20375e7127dac1cfffc2204882be3027023da2d1c303485771bd8265f23185a600ce68963ce6040ce175d4da32f5f23daed0",
          "sha256": "ef01e3b724e7547087d684eeeac0fc733cbbdc259b3485826d26efd23c2a648a",
          "sha1": "3731abb67833c42865f9b96057dc3b16d48c1348",
          "md5": "f3a2e12e842f51c2b7619bfb45c82c1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactive",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-rx3-1.5.0.jar",
          "url": "kotlinx-coroutines-rx3-1.5.0.jar",
          "size": 70612,
          "sha512": "8bf6118be85cb8a4058e59ca1b4a20375e7127dac1cfffc2204882be3027023da2d1c303485771bd8265f23185a600ce68963ce6040ce175d4da32f5f23daed0",
          "sha256": "ef01e3b724e7547087d684eeeac0fc733cbbdc259b3485826d26efd23c2a648a",
          "sha1": "3731abb67833c42865f9b96057dc3b16d48c1348",
          "md5": "f3a2e12e842f51c2b7619bfb45c82c1a"
        }
      ]
    }
  ]
}
