{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "shark-graph",
    "version": "2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-hprof",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "shark-graph-2.12.jar",
          "url": "shark-graph-2.12.jar",
          "size": 167922,
          "sha512": "411fd6be3f2b89136543c84d3e67844eea1de2b48171c1f911b8a83ff1d8ec008ee1c88b1a5dcfb49692c6aabf33d5dda304088ed4aba6457abaf2c2890afc0f",
          "sha256": "2ca78e179ff34923b2b8c326336935f23463a66369833b0c512b2ca0854bbfbb",
          "sha1": "a727f5edd23db7e56e8a5e510fde22dd3f6a273a",
          "md5": "0d81d87b3d5d464118aab20dd3f7b83a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-hprof",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "shark-graph-2.12.jar",
          "url": "shark-graph-2.12.jar",
          "size": 167922,
          "sha512": "411fd6be3f2b89136543c84d3e67844eea1de2b48171c1f911b8a83ff1d8ec008ee1c88b1a5dcfb49692c6aabf33d5dda304088ed4aba6457abaf2c2890afc0f",
          "sha256": "2ca78e179ff34923b2b8c326336935f23463a66369833b0c512b2ca0854bbfbb",
          "sha1": "a727f5edd23db7e56e8a5e510fde22dd3f6a273a",
          "md5": "0d81d87b3d5d464118aab20dd3f7b83a"
        }
      ]
    }
  ]
}
