{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat-resources",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.6.1.aar",
          "url": "appcompat-resources-1.6.1.aar",
          "size": 66329,
          "sha512": "de556a0504427dddebd436ad0d3c433bd276870f007ba0bc56cd74c5692d9f73c2e094d4299563c506c1c46b0dbda22c7379236a350bb419fbabb0fcb5a287d6",
          "sha256": "db915dbf49357863de1669ff9fdd8e9008d65fe357af6cce9ae63043ad5f6617",
          "sha1": "03fe43025e50b556f319b1ff82a730d5a376a31e",
          "md5": "b597bd2dc09202423b3a8b982626508b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.6.1.aar",
          "url": "appcompat-resources-1.6.1.aar",
          "size": 66329,
          "sha512": "de556a0504427dddebd436ad0d3c433bd276870f007ba0bc56cd74c5692d9f73c2e094d4299563c506c1c46b0dbda22c7379236a350bb419fbabb0fcb5a287d6",
          "sha256": "db915dbf49357863de1669ff9fdd8e9008d65fe357af6cce9ae63043ad5f6617",
          "sha1": "03fe43025e50b556f319b1ff82a730d5a376a31e",
          "md5": "b597bd2dc09202423b3a8b982626508b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appcompat-resources-1.6.1-sources.jar",
          "url": "appcompat-resources-1.6.1-sources.jar",
          "size": 40964,
          "sha512": "4e3697f8b7400756471b1dd6b70ca2c48c6f5b29c25a686f0ffc32a69de692c5c2d06e47789753f35ee22b0e6fc336a9ecd20c81d7909319a142478c19d75771",
          "sha256": "cd2dcd239ec449ad6b860d4e8273f01caa633f89bcc0d356d176fc781692d5dc",
          "sha1": "53fccb3cf4bae3905a487581fb3ff7b9616583a6",
          "md5": "d40e26e9f917da368253f0e56797a1a3"
        }
      ]
    }
  ]
}