{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "plumber-android-core",
    "version": "2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-log",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-utils",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "plumber-android-core-2.12.aar",
          "url": "plumber-android-core-2.12.aar",
          "size": 85735,
          "sha512": "2c2b5c8d909ddb00bc2548c03da8136e837cdb98dc097d83f7e29222142cfbdd484d7857e37248f05f05291691fb975f15d45cd129c10e910ce1bdc14b0ec4eb",
          "sha256": "c1215802d2bff1d9cdee1706aa089dd2f64c9dc34dbfd4913f55dbcbcd219ee2",
          "sha1": "c69ec81c80c07adde1eb6226e9946de58761ec4b",
          "md5": "8806c6c44424ae4a7b0632ac8bfcdc81"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-log",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-utils",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.curtains",
          "module": "curtains",
          "version": {
            "requires": "1.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "plumber-android-core-2.12.aar",
          "url": "plumber-android-core-2.12.aar",
          "size": 85735,
          "sha512": "2c2b5c8d909ddb00bc2548c03da8136e837cdb98dc097d83f7e29222142cfbdd484d7857e37248f05f05291691fb975f15d45cd129c10e910ce1bdc14b0ec4eb",
          "sha256": "c1215802d2bff1d9cdee1706aa089dd2f64c9dc34dbfd4913f55dbcbcd219ee2",
          "sha1": "c69ec81c80c07adde1eb6226e9946de58761ec4b",
          "md5": "8806c6c44424ae4a7b0632ac8bfcdc81"
        }
      ]
    }
  ]
}
