{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "leakcanary-object-watcher-android-androidx",
    "version": "2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android-core",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-object-watcher-android-androidx-2.12.aar",
          "url": "leakcanary-object-watcher-android-androidx-2.12.aar",
          "size": 9957,
          "sha512": "aa98a3659bc0d0eecb3a5dfbfb3abfffe41fbd4711d10517ffe822a1a897be211f6ededa4dc4d905912cf2d0b4f3f9fcdb5f77a11b569bac77c7992045cca33a",
          "sha256": "d853a58f6f9bdbf574893f56cc9dabbde03ef55ae998d9be57b573fdb2289edb",
          "sha1": "f5edb2f30bf98b5ce5c89d48098959de53151cb6",
          "md5": "45f5b49da46298080c3f2c857f292833"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android-core",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-object-watcher-android-androidx-2.12.aar",
          "url": "leakcanary-object-watcher-android-androidx-2.12.aar",
          "size": 9957,
          "sha512": "aa98a3659bc0d0eecb3a5dfbfb3abfffe41fbd4711d10517ffe822a1a897be211f6ededa4dc4d905912cf2d0b4f3f9fcdb5f77a11b569bac77c7992045cca33a",
          "sha256": "d853a58f6f9bdbf574893f56cc9dabbde03ef55ae998d9be57b573fdb2289edb",
          "sha1": "f5edb2f30bf98b5ce5c89d48098959de53151cb6",
          "md5": "45f5b49da46298080c3f2c857f292833"
        }
      ]
    }
  ]
}
