{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-samples",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-lint",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-lint",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.7.2.aar",
          "url": "activity-1.7.2.aar",
          "size": 142726,
          "sha512": "d6d1fa3146728a3da3757a7150164744f4bed8b246ac3517c2467a1f037edb6ca5c4a3aacd93d4e6d7bcb82c0366b202657a19121e5d153b60ee8ebdf6c51540",
          "sha256": "2a1abf8e0a598d246b1edcb71e2395e39f32332195ebe5ea40a3dd21355ba3ae",
          "sha1": "e389e8ec8d78db0e45dec445d5cbeb0a05323295",
          "md5": "56a91eb5d3a2866bd8c24e74e7de5925"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-samples",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-lint",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-lint",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.7.2.aar",
          "url": "activity-1.7.2.aar",
          "size": 142726,
          "sha512": "d6d1fa3146728a3da3757a7150164744f4bed8b246ac3517c2467a1f037edb6ca5c4a3aacd93d4e6d7bcb82c0366b202657a19121e5d153b60ee8ebdf6c51540",
          "sha256": "2a1abf8e0a598d246b1edcb71e2395e39f32332195ebe5ea40a3dd21355ba3ae",
          "sha1": "e389e8ec8d78db0e45dec445d5cbeb0a05323295",
          "md5": "56a91eb5d3a2866bd8c24e74e7de5925"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-samples",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-lint",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-lint",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.7.2-sources.jar",
          "url": "activity-1.7.2-sources.jar",
          "size": 49127,
          "sha512": "0765855c10a5d9c78a2a7fe552119157028700d06b06cf21853de38a6f46324965e0c4169c01b3b7ff560c0c781e8473a87321c69457dca91cf397c62d422a7c",
          "sha256": "a400c7ca4d972e5e6884d78d9dc4f1d4dfc95fe5afcd92fabde47e4d496cae5d",
          "sha1": "02f5e8ceeb74490d8c6d12bdd94dcca61bfaf5a4",
          "md5": "efd826c2f4830af11571677cadca106e"
        }
      ]
    }
  ]
}