{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core",
    "version": "1.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.10.1.aar",
          "url": "core-1.10.1.aar",
          "size": 1248663,
          "sha512": "4d58f4b32b343270233bf4fb910035cc8214e4b4a4ece4a143e0971e4fda361ee2f358bbb24fbe1c4730d39763831e1e84b40dedbd19fc49ef40ecc6d492abd8",
          "sha256": "21478735c79de8eb8b464a6bd51d866c9939171f974887471c9d197e37fd6bad",
          "sha1": "b20f6712d783963a13773be934b59b286041a667",
          "md5": "1c491bd3e3be85602318b645e5253d3b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.10.1.aar",
          "url": "core-1.10.1.aar",
          "size": 1248663,
          "sha512": "4d58f4b32b343270233bf4fb910035cc8214e4b4a4ece4a143e0971e4fda361ee2f358bbb24fbe1c4730d39763831e1e84b40dedbd19fc49ef40ecc6d492abd8",
          "sha256": "21478735c79de8eb8b464a6bd51d866c9939171f974887471c9d197e37fd6bad",
          "sha1": "b20f6712d783963a13773be934b59b286041a667",
          "md5": "1c491bd3e3be85602318b645e5253d3b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.10.1-sources.jar",
          "url": "core-1.10.1-sources.jar",
          "size": 883581,
          "sha512": "15977376480e56e1daca51e62cf3799800d1e5a97a9ae7099d27b319a2622d82de44c49060117b52f278b7893a5614e8fe30cc5f389622fd607610e38eda76a4",
          "sha256": "0e1e079c9fad49e2f6262e334d99c1a4107de254c0d434c3338f9e2279686cae",
          "sha1": "1dfbeafef6d1a3fcb7d75df4925c4122c04b9790",
          "md5": "ce1404653f89e58928b422f39e31fac9"
        }
      ]
    }
  ]
}