{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.savedstate",
    "module": "savedstate",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-1.2.0.aar",
          "url": "savedstate-1.2.0.aar",
          "size": 19326,
          "sha512": "268b8aa85e7e8f0ea9598dd836b74444d53bc0d19a14b7ecb8c86802091743c1386cc770d6891f7b88595029f7688c5228f0786808de19d9e44f1e7997f717f7",
          "sha256": "2de528d6898e95ef020d22d9ffdf9d1f77cbdd93f92d39dfaa5d5c43b0c311c8",
          "sha1": "bcaeef765339b976946cc9e891536713af651ebc",
          "md5": "5b241c016c43dd2e85fdda32119ac1fb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-1.2.0.aar",
          "url": "savedstate-1.2.0.aar",
          "size": 19326,
          "sha512": "268b8aa85e7e8f0ea9598dd836b74444d53bc0d19a14b7ecb8c86802091743c1386cc770d6891f7b88595029f7688c5228f0786808de19d9e44f1e7997f717f7",
          "sha256": "2de528d6898e95ef020d22d9ffdf9d1f77cbdd93f92d39dfaa5d5c43b0c311c8",
          "sha1": "bcaeef765339b976946cc9e891536713af651ebc",
          "md5": "5b241c016c43dd2e85fdda32119ac1fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "savedstate-1.2.0-sources.jar",
          "url": "savedstate-1.2.0-sources.jar",
          "size": 8863,
          "sha512": "e59da08967bc69c1387208fa2e0a11c98a53bf2b252540207da7915cce1a8e97d3073e3aa4f31a1b986e876bf6dbaedc38d963c5562242d24bc9d28a3c0b185a",
          "sha256": "27056b2a9cddc7e5dc73700771f4e8dddbbcbab52b6cb46e33edc9588337e1cd",
          "sha1": "fce79e03fd65c3734d1c9364244456d89d336810",
          "md5": "4216af3a5bd0fb4ab22b682db63c615c"
        }
      ]
    }
  ]
}