{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "leakcanary-object-watcher-android-core",
    "version": "2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-utils",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-object-watcher-android-core-2.12.aar",
          "url": "leakcanary-object-watcher-android-core-2.12.aar",
          "size": 50852,
          "sha512": "ab23de8c9135d1bfe78680207614477eccc9ff4681b29b632af0d25b9417610872480bbb763a01211b6dad4960b795c34d4568e6edc3fd3115dc1ae3bf8c0d71",
          "sha256": "4a1b32588657ba960c09df1bff04c78872bde038565552da8bc148d69ae41cf2",
          "sha1": "e35417ac55943343b0fc7f8789a25cba1e30ff30",
          "md5": "06ef2d3ed39c21492ff907e4a4170c57"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-utils",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "com.squareup.curtains",
          "module": "curtains",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-object-watcher-android-core-2.12.aar",
          "url": "leakcanary-object-watcher-android-core-2.12.aar",
          "size": 50852,
          "sha512": "ab23de8c9135d1bfe78680207614477eccc9ff4681b29b632af0d25b9417610872480bbb763a01211b6dad4960b795c34d4568e6edc3fd3115dc1ae3bf8c0d71",
          "sha256": "4a1b32588657ba960c09df1bff04c78872bde038565552da8bc148d69ae41cf2",
          "sha1": "e35417ac55943343b0fc7f8789a25cba1e30ff30",
          "md5": "06ef2d3ed39c21492ff907e4a4170c57"
        }
      ]
    }
  ]
}
