{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "leakcanary-object-watcher-android",
    "version": "2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android-core",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-object-watcher-android-2.12.aar",
          "url": "leakcanary-object-watcher-android-2.12.aar",
          "size": 3526,
          "sha512": "542d6a758e27c0c2c8e0c6c7f65af85be38bc82746a97a9fe015f187e243884633d89c72aad699a67667eb74a45ca729c53249f81f1c7aeb5f4b4d64e3543a6a",
          "sha256": "a5fa2035838b9b91dbe9e75e30285dbc3c7285d25c6bcd0d359c4c35584d18b6",
          "sha1": "a0b74352533a3bc04fe9c2362cbf6b853d18e252",
          "md5": "350b304a8c62b188f83fe3d11a5b4764"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android-core",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-object-watcher-android-2.12.aar",
          "url": "leakcanary-object-watcher-android-2.12.aar",
          "size": 3526,
          "sha512": "542d6a758e27c0c2c8e0c6c7f65af85be38bc82746a97a9fe015f187e243884633d89c72aad699a67667eb74a45ca729c53249f81f1c7aeb5f4b4d64e3543a6a",
          "sha256": "a5fa2035838b9b91dbe9e75e30285dbc3c7285d25c6bcd0d359c4c35584d18b6",
          "sha1": "a0b74352533a3bc04fe9c2362cbf6b853d18e252",
          "md5": "350b304a8c62b188f83fe3d11a5b4764"
        }
      ]
    }
  ]
}
