{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "window-1.0.0.aar",
          "url": "window-1.0.0.aar",
          "size": 160998,
          "sha512": "f2e94205c56a6daa75054b099d7508ce66c8950053dd026cb7b4d32face98c59466ce83fb09a7d43b0409025d5287928596b9a27b79a55302edc7ff1671166d1",
          "sha256": "3212985be4127373ca4d0ea7f8b81a250ae2105e924f7940105d067a0f9ac130",
          "sha1": "b88a4cb0db4e04827baad7b7d45f57d80e84d08e",
          "md5": "f7fb20b90b9ef84a5a9fd9ad5e44ad42"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "window-1.0.0.aar",
          "url": "window-1.0.0.aar",
          "size": 160998,
          "sha512": "f2e94205c56a6daa75054b099d7508ce66c8950053dd026cb7b4d32face98c59466ce83fb09a7d43b0409025d5287928596b9a27b79a55302edc7ff1671166d1",
          "sha256": "3212985be4127373ca4d0ea7f8b81a250ae2105e924f7940105d067a0f9ac130",
          "sha1": "b88a4cb0db4e04827baad7b7d45f57d80e84d08e",
          "md5": "f7fb20b90b9ef84a5a9fd9ad5e44ad42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "window-1.0.0-sources.jar",
          "url": "window-1.0.0-sources.jar",
          "size": 66779,
          "sha512": "e67bb5d681324aebd97b8162ca16139bcbc1e88e8360c50ef029cb87c4c57d5ba1be9b8699d13c20a0587a80ea6f8f6be78d5aea4b4fd5faee47ef0a27c407cd",
          "sha256": "9c68ea6f87898cdb1bd0ddf6ed7f20715f7fd54727749ef00f3e73b75f5ea66a",
          "sha1": "5a4929a59cb71e7c184259f2e088e1be36375f94",
          "md5": "ae4092f9fbf890981c3276936c5797d8"
        }
      ]
    }
  ]
}
