{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.constraintlayout",
    "module": "constraintlayout-core",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "constraintlayout-core-1.0.4.jar",
          "url": "constraintlayout-core-1.0.4.jar",
          "size": 443912,
          "sha512": "2fcf300d60069eee759abe01902115c94b3c0cb2268defcd705efd4c2c99cb823dfcdd463c4323e0ac200123b29349bc5a919b8776052e2cef15a45763d0cc65",
          "sha256": "3e477f4de231e58b25f5a992f3be45e97d332c34a39a9e3e7d4b78ae0ac2256f",
          "sha1": "29cdbe03ded6b0980f63fa5da2579a430e911c40",
          "md5": "23821814bc3beb7570a2e5036f60fd65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "constraintlayout-core-1.0.4.jar",
          "url": "constraintlayout-core-1.0.4.jar",
          "size": 443912,
          "sha512": "2fcf300d60069eee759abe01902115c94b3c0cb2268defcd705efd4c2c99cb823dfcdd463c4323e0ac200123b29349bc5a919b8776052e2cef15a45763d0cc65",
          "sha256": "3e477f4de231e58b25f5a992f3be45e97d332c34a39a9e3e7d4b78ae0ac2256f",
          "sha1": "29cdbe03ded6b0980f63fa5da2579a430e911c40",
          "md5": "23821814bc3beb7570a2e5036f60fd65"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "constraintlayout-core-1.0.4-sources.jar",
          "url": "constraintlayout-core-1.0.4-sources.jar",
          "size": 273677,
          "sha512": "6aeb4eec27f19c9743c1355cb5770e754b2f190ba8276057cf693ec151b96c023f38e65e3464b5f87450fcf63a58bd83e82f7f477cf0e7aee4b2167b2b392fb5",
          "sha256": "909577619c082fb1ccca81a56628e91f8880e1cb9952585ecc678422f9706384",
          "sha1": "c106454e3be0328945d43b2ff5da751518cf0d3e",
          "md5": "b652d1c6ac6dac4cdb6298ee330ca525"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "constraintlayout-core-1.0.4-javadoc.jar",
          "url": "constraintlayout-core-1.0.4-javadoc.jar",
          "size": 612034,
          "sha512": "7e2caef607818339e03b2eafbfd262175139d8faea2a7c11d0ad5d0729043f98547eb8c2c2a223400ab38d7484d4dda4db2f0c7b4a2d2231c911545210deb0c3",
          "sha256": "64b86629ea9173e32ad6b816c3569832de7cfadb9e8720c7ded0dc38881e6629",
          "sha1": "ac814192f8c7f4be889a4bc070207f4dde7cf14a",
          "md5": "b76864e588e3c9544e2f86d92a8f93d7"
        }
      ]
    }
  ]
}
