{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.annotation",
    "module": "annotation-experimental",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-experimental-1.3.0.aar",
          "url": "annotation-experimental-1.3.0.aar",
          "size": 36019,
          "sha512": "fb738457a504d75e742f3de92cd32d37c9199747816274841d9dd7eb57343afa6e76e45c6aa1ea161187d15d2d4c396ea601fa3bbab69f75f09e5c48e7ee643a",
          "sha256": "abfd29c8556e5bd0325a9f769ab9e9d154ff4a5515c476cdd5a2a8285b1b19dc",
          "sha1": "5087c6f545117dcd474e69e1a93cacec9d7334af",
          "md5": "c6a6f00afdb749962ac82bd42deb6544"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-experimental-1.3.0.aar",
          "url": "annotation-experimental-1.3.0.aar",
          "size": 36019,
          "sha512": "fb738457a504d75e742f3de92cd32d37c9199747816274841d9dd7eb57343afa6e76e45c6aa1ea161187d15d2d4c396ea601fa3bbab69f75f09e5c48e7ee643a",
          "sha256": "abfd29c8556e5bd0325a9f769ab9e9d154ff4a5515c476cdd5a2a8285b1b19dc",
          "sha1": "5087c6f545117dcd474e69e1a93cacec9d7334af",
          "md5": "c6a6f00afdb749962ac82bd42deb6544"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-experimental-1.3.0-sources.jar",
          "url": "annotation-experimental-1.3.0-sources.jar",
          "size": 5545,
          "sha512": "b8ffeccbd06483db44ea8b71e2cb390e970a8ee99454aadad75cd743ad6e0a2cc10471eb9364a3a983fc69e3c1e0635060ca8fcd429c34a4f4332fc2484d40db",
          "sha256": "90ea2761129cfe76516171e6b26f7c016178b97828ddc85cdfdd5f6e83e40d35",
          "sha1": "56ca4da0948c085ca4bb0e6077e01a3ab1298dfb",
          "md5": "b35dfb2206cdc1f4f80ae61e28226d1a"
        }
      ]
    }
  ]
}