{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-runtime",
    "version": "2.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.8.1.aar",
          "url": "work-runtime-2.8.1.aar",
          "size": 1665132,
          "sha512": "3a5685f8051d2bb743980e9b7e4f6f87099a104ed0c859cacaa4955ab58fbe3e21110cd74375c7ba23d0b3f4760be34a273002f33ec41528fc934c9717316080",
          "sha256": "26d9d5622a0d69c2b601cb661ea175f6e0b54db2753711b18ca136be4b9ae9c2",
          "sha1": "93cf8448789a8a2abf56c11a71e8cfda9f6647e4",
          "md5": "09587bd2bc81b509367af838606b5e8d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-2.8.1.aar",
          "url": "work-runtime-2.8.1.aar",
          "size": 1665132,
          "sha512": "3a5685f8051d2bb743980e9b7e4f6f87099a104ed0c859cacaa4955ab58fbe3e21110cd74375c7ba23d0b3f4760be34a273002f33ec41528fc934c9717316080",
          "sha256": "26d9d5622a0d69c2b601cb661ea175f6e0b54db2753711b18ca136be4b9ae9c2",
          "sha1": "93cf8448789a8a2abf56c11a71e8cfda9f6647e4",
          "md5": "09587bd2bc81b509367af838606b5e8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-runtime-2.8.1-sources.jar",
          "url": "work-runtime-2.8.1-sources.jar",
          "size": 268422,
          "sha512": "758091c3d329f0c299e5fdbadf90256d25f6943a4e75966b790c690152531e3836627de963058a70d3bc002ef7c5eeca63514d76f248f38a91856ea22d907371",
          "sha256": "9a942a760c79e9a9712daf3d343d5f5219c47ec58e6fce58dd7f906955bcca5a",
          "sha1": "2f6009c665ff8ab1f96495461b215b6623a93701",
          "md5": "d268ca00231bcad211f0e6075dbae65e"
        }
      ]
    }
  ]
}