{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "plumber-android",
    "version": "2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "plumber-android-core",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "plumber-android-2.12.aar",
          "url": "plumber-android-2.12.aar",
          "size": 4774,
          "sha512": "0e6eb67515075f9f0bd58ec749a990458cb17612f470b5e774622118320e292a84fb61e6a066c43a4455661712d87b6b6ca2fb3734757feea9a6551f19e4967e",
          "sha256": "deccc6849f6b84788f4fdbce5cc05c3d5a029aa365902cbb28426a21e3cdf7ac",
          "sha1": "9e5542e307cf7056453cf66a6756a64df576232b",
          "md5": "60a79189d9bdfc735455b6c473f61fb3"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "plumber-android-core",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "plumber-android-2.12.aar",
          "url": "plumber-android-2.12.aar",
          "size": 4774,
          "sha512": "0e6eb67515075f9f0bd58ec749a990458cb17612f470b5e774622118320e292a84fb61e6a066c43a4455661712d87b6b6ca2fb3734757feea9a6551f19e4967e",
          "sha256": "deccc6849f6b84788f4fdbce5cc05c3d5a029aa365902cbb28426a21e3cdf7ac",
          "sha1": "9e5542e307cf7056453cf66a6756a64df576232b",
          "md5": "60a79189d9bdfc735455b6c473f61fb3"
        }
      ]
    }
  ]
}
