{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "shark",
    "version": "2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-graph",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "shark-2.12.jar",
          "url": "shark-2.12.jar",
          "size": 355940,
          "sha512": "4bf8a4188d9649bb6c617ecbf84d65ffae9a9b694a6f462b89bcf59bdf4b40c3653c2b327b2da872186b2d7cfbefa5a179d2acb5b6b569da23a91917fe6dfaea",
          "sha256": "e58f2311ec216805a166267e23dce2d68c7a68b234ad559777d806c38144bd6e",
          "sha1": "c6c6b436fa7e4231179ba1143e5dc54da59b6b15",
          "md5": "b1ecd8d55e49ca27e94128a4c963d075"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-graph",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "shark-2.12.jar",
          "url": "shark-2.12.jar",
          "size": 355940,
          "sha512": "4bf8a4188d9649bb6c617ecbf84d65ffae9a9b694a6f462b89bcf59bdf4b40c3653c2b327b2da872186b2d7cfbefa5a179d2acb5b6b569da23a91917fe6dfaea",
          "sha256": "e58f2311ec216805a166267e23dce2d68c7a68b234ad559777d806c38144bd6e",
          "sha1": "c6c6b436fa7e4231179ba1143e5dc54da59b6b15",
          "md5": "b1ecd8d55e49ca27e94128a4c963d075"
        }
      ]
    }
  ]
}
