{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "leakcanary-object-watcher",
    "version": "2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-log",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-object-watcher-2.12.jar",
          "url": "leakcanary-object-watcher-2.12.jar",
          "size": 16911,
          "sha512": "0c72e52bb332e4405d182365f65bb9257f509a8d6230a5a78c4840728f1d9a0035a34a253e3fac1a0ff27d5627707da743e32cc70a8d856b965c72a1c6797fd8",
          "sha256": "f37a7597e72a7cf4039665d3426cbd0dd2588a443e5878d1a5813688fb86359a",
          "sha1": "0176333d33ac9aa73e7164034355f82b1c3efcf7",
          "md5": "703e41366ab9cb23f9022b446566ef0f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-log",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-object-watcher-2.12.jar",
          "url": "leakcanary-object-watcher-2.12.jar",
          "size": 16911,
          "sha512": "0c72e52bb332e4405d182365f65bb9257f509a8d6230a5a78c4840728f1d9a0035a34a253e3fac1a0ff27d5627707da743e32cc70a8d856b965c72a1c6797fd8",
          "sha256": "f37a7597e72a7cf4039665d3426cbd0dd2588a443e5878d1a5813688fb86359a",
          "sha1": "0176333d33ac9aa73e7164034355f82b1c3efcf7",
          "md5": "703e41366ab9cb23f9022b446566ef0f"
        }
      ]
    }
  ]
}
