{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-reactive",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "dhafiarkonhbfll4adozkt6cc4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-reactive-1.5.0.jar",
          "url": "kotlinx-coroutines-reactive-1.5.0.jar",
          "size": 63148,
          "sha512": "4e79e155c843a2aa43b0d01989a98c7e6720755c6b105803db6f662b7c5fc2529eadfed7763ff73c9cd2b1184c5b0b5dd79acff4e076e426dc50efd9d8adc0c5",
          "sha256": "6d9e7e91bf527a3425d4a40c8b9946a61bcc970a13f05bd2d0ce62f4344fff6a",
          "sha1": "4e68a7d021b3a79632f2e746b410b955f0931e05",
          "md5": "184e82eab644a10cd9b4d4f9977d9d0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-reactive-1.5.0.jar",
          "url": "kotlinx-coroutines-reactive-1.5.0.jar",
          "size": 63148,
          "sha512": "4e79e155c843a2aa43b0d01989a98c7e6720755c6b105803db6f662b7c5fc2529eadfed7763ff73c9cd2b1184c5b0b5dd79acff4e076e426dc50efd9d8adc0c5",
          "sha256": "6d9e7e91bf527a3425d4a40c8b9946a61bcc970a13f05bd2d0ce62f4344fff6a",
          "sha1": "4e68a7d021b3a79632f2e746b410b955f0931e05",
          "md5": "184e82eab644a10cd9b4d4f9977d9d0b"
        }
      ]
    }
  ]
}
