{
  "formatVersion": "1.1",
  "component": {
    "group": "org.checkerframework",
    "module": "checker-qual",
    "version": "3.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "smklfgl3h5et3hv6dg43gj3eoq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "checker-qual-3.12.0.jar",
          "url": "checker-qual-3.12.0.jar",
          "size": 208835,
          "sha512": "ff20c424e130c31c30b4f4f5b4374f8f98f94ddae2b123f3c213f147be6b3de57854ee5651b02dd97d352c1c1df2a8bfeef73d5307a71372f46a6002eab24d78",
          "sha256": "ff10785ac2a357ec5de9c293cb982a2cbb605c0309ea4cc1cb9b9bc6dbe7f3cb",
          "sha1": "d5692f0526415fcc6de94bb5bfbd3afd9dd3b3e5",
          "md5": "ab1ae0e2f2f63601597a5a96fca8a54f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.12.0.jar",
          "url": "checker-qual-3.12.0.jar",
          "size": 208835,
          "sha512": "ff20c424e130c31c30b4f4f5b4374f8f98f94ddae2b123f3c213f147be6b3de57854ee5651b02dd97d352c1c1df2a8bfeef73d5307a71372f46a6002eab24d78",
          "sha256": "ff10785ac2a357ec5de9c293cb982a2cbb605c0309ea4cc1cb9b9bc6dbe7f3cb",
          "sha1": "d5692f0526415fcc6de94bb5bfbd3afd9dd3b3e5",
          "md5": "ab1ae0e2f2f63601597a5a96fca8a54f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.12.0-javadoc.jar",
          "url": "checker-qual-3.12.0-javadoc.jar",
          "size": 900991,
          "sha512": "86b792d35ea092e69527e68c9c28d3ad09b9227f18922a3109f4acdbc8190014446660bf604a77c3abf5f64c0e5d764b7245f645f02c0f95a398e0351feaa786",
          "sha256": "760ed10dff3a7fdf617e2591949e7831995a959a132572a63529c6562800aa89",
          "sha1": "fd7626f12ccbe6f5557a00cd13c7d399789723cf",
          "md5": "eb6316611d758839017a97930ab4c02f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.12.0-sources.jar",
          "url": "checker-qual-3.12.0-sources.jar",
          "size": 237067,
          "sha512": "fd004718c3230332f468602787ef99b6089df20f78df18d12ffcb20145b0c37f2e01a03212661403eeb7c74e9c221c328980148d01df364f23680aa4d0bcbb0e",
          "sha256": "fd99a45195ed893803624d1030387056a96601013f5e61ccabd79abb4ddfa876",
          "sha1": "10dacb8b36398debceca36cd0db5f3316967f80e",
          "md5": "ccde79e4218681aef564a5ec2f87cd60"
        }
      ]
    }
  ]
}
