{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-common",
    "version": "2.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "room-common-2.5.2.jar",
          "url": "room-common-2.5.2.jar",
          "size": 60225,
          "sha512": "cefd6f474848e9c85e8ec7bb9e6f16f89f816ecfd5e46e9d1b48fba3efd164414e1ffe44f2982f305a610221d1ed0abdc2aa67a8130d9394e73403be7b9dc6f8",
          "sha256": "0262e2a0e2a2e9c7267b9f7a405847ce636a06c4c16c52976cb68df77866b87d",
          "sha1": "0829a83fb92f1696a8a32f3beea884dfc87b2693",
          "md5": "809882326516ae74ccc0121bcfcb29c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "room-common-2.5.2.jar",
          "url": "room-common-2.5.2.jar",
          "size": 60225,
          "sha512": "cefd6f474848e9c85e8ec7bb9e6f16f89f816ecfd5e46e9d1b48fba3efd164414e1ffe44f2982f305a610221d1ed0abdc2aa67a8130d9394e73403be7b9dc6f8",
          "sha256": "0262e2a0e2a2e9c7267b9f7a405847ce636a06c4c16c52976cb68df77866b87d",
          "sha1": "0829a83fb92f1696a8a32f3beea884dfc87b2693",
          "md5": "809882326516ae74ccc0121bcfcb29c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-common-2.5.2-sources.jar",
          "url": "room-common-2.5.2-sources.jar",
          "size": 59845,
          "sha512": "933d8f8cb47ea264df5def0aafed1bee1b9c65741ef755dad6359800112a8e6e2edee0ab313c8f8015590fdcfb61100e0c6c720f15980de3a991aa10654c0508",
          "sha256": "99fc0e00a728b55667cbec4a0af2c5c375cb0b41791b103c0015e537bbbdcb2f",
          "sha1": "913bba9280278d05943a4bf9173516323cb63c45",
          "md5": "d7c4734fe765f95c381657a74930d952"
        }
      ]
    }
  ]
}