{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.annotation",
    "module": "annotation",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "annotation-1.3.0.jar",
          "url": "annotation-1.3.0.jar",
          "size": 31705,
          "sha512": "63def0a638a01e3b04abf515b27b5250c24b9f95db0b08dde7c27094e1ebdfca79642fd06938843794827400ac1fd437e0f80881350f44adf1fef0e8f177a12f",
          "sha256": "97dc45afefe3a1e421da42b8b6e9f90491477c45fc6178203e3a5e8a05ee8553",
          "sha1": "021f49f5f9b85fc49de712539f79123119740595",
          "md5": "a65958ba342e73cd31b9246352ce732a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-1.3.0.jar",
          "url": "annotation-1.3.0.jar",
          "size": 31705,
          "sha512": "63def0a638a01e3b04abf515b27b5250c24b9f95db0b08dde7c27094e1ebdfca79642fd06938843794827400ac1fd437e0f80881350f44adf1fef0e8f177a12f",
          "sha256": "97dc45afefe3a1e421da42b8b6e9f90491477c45fc6178203e3a5e8a05ee8553",
          "sha1": "021f49f5f9b85fc49de712539f79123119740595",
          "md5": "a65958ba342e73cd31b9246352ce732a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-1.3.0-sources.jar",
          "url": "annotation-1.3.0-sources.jar",
          "size": 59743,
          "sha512": "b04838a5dc06b82db337e15eff2e6d56d504aaf95363643fc53a11ccabcd2905084403c59dea656b405a8e444726277469becadd1a66e2368c6d926fefb74b87",
          "sha256": "f3f818e76da236bb419bf90bdf86be49349f0f601a13cc2e735c00504f7f6090",
          "sha1": "661529c7dfdacef81b03e6dd27e5daa73793a9b2",
          "md5": "30cfdfe89a0c7a8d17ed650ad6200115"
        }
      ]
    }
  ]
}
