{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-samples",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-lint",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-lint",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.7.2.aar",
          "url": "activity-ktx-1.7.2.aar",
          "size": 26400,
          "sha512": "100602ff5eb9228f11021375c9d84fcbe4b4f372293df35d8a752f93b535d429a53f94a38391a152685b6a2e6f0c760feeec86d62dee8ad044792604dc33a314",
          "sha256": "b0b4206ece92919925061fdf5784dd21f0118534609e8f6d9404bdd0f5cb5a3d",
          "sha1": "aa5446612734838a88a81be2f9d68797b2943350",
          "md5": "d10d4ffb35569c233c6e229fbda56b96"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-samples",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-lint",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-lint",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.7.2.aar",
          "url": "activity-ktx-1.7.2.aar",
          "size": 26400,
          "sha512": "100602ff5eb9228f11021375c9d84fcbe4b4f372293df35d8a752f93b535d429a53f94a38391a152685b6a2e6f0c760feeec86d62dee8ad044792604dc33a314",
          "sha256": "b0b4206ece92919925061fdf5784dd21f0118534609e8f6d9404bdd0f5cb5a3d",
          "sha1": "aa5446612734838a88a81be2f9d68797b2943350",
          "md5": "d10d4ffb35569c233c6e229fbda56b96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-samples",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose-lint",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-lint",
          "version": {
            "requires": "1.7.2"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.7.2-sources.jar",
          "url": "activity-ktx-1.7.2-sources.jar",
          "size": 5891,
          "sha512": "0ab223f5f772f37a5e9d647b10c1e1addc94a60bd1cc23067b0fb4b10d1c035df41326f1ffbaac47d33acb338d9c2eb76288a1acd104c9713eff54de9735024c",
          "sha256": "aa0efa1286eca31f19921e14807731242ac606ddcc8588c1b10550f2293dd6c6",
          "sha1": "303ffe73fa85353c185e2281d60fb8fc65be8bc8",
          "md5": "c6e340fecd1713a2be35815d65373ff0"
        }
      ]
    }
  ]
}