{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-1.6.1.aar",
          "url": "appcompat-1.6.1.aar",
          "size": 1135853,
          "sha512": "7f48ed714deeda7a8956edfda70e7b4c72198316f6e3f6ae049acd1f033762d2ac34fe20cffcf4067410d05736d95eea4fad6a3493b9032f8fb4034b1fda7498",
          "sha256": "7ea5573b93ababd3bd32312451c6ea48a662b03a140dda81aebe75776a20a422",
          "sha1": "6c7577004b7ebbee5ed87d512b578dd20e3c8c31",
          "md5": "ccc362b1e6d93ca72726b05ce1b074f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.3.6"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.resourceinspection",
          "module": "resourceinspection-annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-1.6.1.aar",
          "url": "appcompat-1.6.1.aar",
          "size": 1135853,
          "sha512": "7f48ed714deeda7a8956edfda70e7b4c72198316f6e3f6ae049acd1f033762d2ac34fe20cffcf4067410d05736d95eea4fad6a3493b9032f8fb4034b1fda7498",
          "sha256": "7ea5573b93ababd3bd32312451c6ea48a662b03a140dda81aebe75776a20a422",
          "sha1": "6c7577004b7ebbee5ed87d512b578dd20e3c8c31",
          "md5": "ccc362b1e6d93ca72726b05ce1b074f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appcompat-1.6.1-sources.jar",
          "url": "appcompat-1.6.1-sources.jar",
          "size": 502833,
          "sha512": "20e02796d219d4b7030a554cc7c1b23ccf27c4d90bbb9fa3ed8ad96f0679ac0ae3f35b13c47752039323d12c7171e98e4c7ca8a17c9a98009798d820da39eb8b",
          "sha256": "c77e0f6d041b918dcfab1ab3bbe080ff5ddbb28352ca42b57fd5a049f02dd5c4",
          "sha1": "ace9a78b961165396147e8691faa18c1b0e48e20",
          "md5": "b51a1d1e16f72cef85ff4c9d677a5cf3"
        }
      ]
    }
  ]
}