{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.constraintlayout",
    "module": "constraintlayout",
    "version": "2.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "constraintlayout-2.1.4.aar",
          "url": "constraintlayout-2.1.4.aar",
          "size": 476596,
          "sha512": "12b377264ae52776a41183881a6947cf9c6d53fef2fe98eef4e1bf4e4a03782b2aebe8fb578048a3938f0514246fd30601d436fe1fbaba444b3164af1bdccc00",
          "sha256": "0df714c0b51e54710ebf746eb469d333176bbb3cb29f80775dc3ca4eb3162512",
          "sha1": "0b7ad5eca28aa9e7c4ea1a7e256c7ee4401a031f",
          "md5": "c7694aeadf54bc50258e3f1481c797e1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout-core",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "constraintlayout-2.1.4.aar",
          "url": "constraintlayout-2.1.4.aar",
          "size": 476596,
          "sha512": "12b377264ae52776a41183881a6947cf9c6d53fef2fe98eef4e1bf4e4a03782b2aebe8fb578048a3938f0514246fd30601d436fe1fbaba444b3164af1bdccc00",
          "sha256": "0df714c0b51e54710ebf746eb469d333176bbb3cb29f80775dc3ca4eb3162512",
          "sha1": "0b7ad5eca28aa9e7c4ea1a7e256c7ee4401a031f",
          "md5": "c7694aeadf54bc50258e3f1481c797e1"
        }
      ]
    }
  ]
}
