{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "leakcanary-object-watcher-android-support-fragments",
    "version": "2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android-core",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-object-watcher-android-support-fragments-2.12.aar",
          "url": "leakcanary-object-watcher-android-support-fragments-2.12.aar",
          "size": 5290,
          "sha512": "4be3630426f51865e57c0db28b99847c9d4a7d53e8e7cd48db6ea0a5c065cfdd80205dc26b6ca49b2e10b0c5ddf0891b7c089e6c93e39aac07e405babd82e70d",
          "sha256": "32ef945b5a63c43772290867191a85030743f9401b83641d7a29a5c81b8fbb88",
          "sha1": "18d1cb2d7b6c3271d02d3e7f39da91c99d8680ea",
          "md5": "aa625412d6af916fa68502d23098b86a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android-core",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-object-watcher-android-support-fragments-2.12.aar",
          "url": "leakcanary-object-watcher-android-support-fragments-2.12.aar",
          "size": 5290,
          "sha512": "4be3630426f51865e57c0db28b99847c9d4a7d53e8e7cd48db6ea0a5c065cfdd80205dc26b6ca49b2e10b0c5ddf0891b7c089e6c93e39aac07e405babd82e70d",
          "sha256": "32ef945b5a63c43772290867191a85030743f9401b83641d7a29a5c81b8fbb88",
          "sha1": "18d1cb2d7b6c3271d02d3e7f39da91c99d8680ea",
          "md5": "aa625412d6af916fa68502d23098b86a"
        }
      ]
    }
  ]
}
