{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "dhafiarkonhbfll4adozkt6cc4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-metadata-1.5.0-all.jar",
          "url": "kotlinx-coroutines-core-1.5.0-all.jar",
          "size": 78534,
          "sha512": "0e86b8db30793cc412439df168aa4228e20bc5f8df6432adbab51273d63a58a67784d73029937f2f075702f4600cdca7883128d12511d53c4791d122d4b42482",
          "sha256": "fd58f72f025aa044b09b8b18299012f0d5710632834bcfab3aee32d3b1f26a88",
          "sha1": "2685819c001396957150e0439b9d597eaa42b2bf",
          "md5": "1473d3808a18b351ad523ee2c104e632"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-1.5.0.jar",
          "url": "kotlinx-coroutines-core-1.5.0.jar",
          "size": 168531,
          "sha512": "ab44e8f30873750ebc2754c928fcdf35e0657b79293488a9f01af68e617a419860b5360e2b9e8d27d087e11c29cbd263e1d00fdd682b9389ea6904fb9135d6c1",
          "sha256": "6f738012913d3d4bc18408a5011108d4744a72b6233662ee4d4dd50da9550b8d",
          "sha1": "4d16638ba448821e65a99830310c43863bff25b9",
          "md5": "33a98ceff78b73b413e2474e738b21ea"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosarm32/1.5.0/kotlinx-coroutines-core-iosarm32-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosarm32",
        "version": "1.5.0"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosarm32/1.5.0/kotlinx-coroutines-core-iosarm32-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosarm32",
        "version": "1.5.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosarm64/1.5.0/kotlinx-coroutines-core-iosarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosarm64/1.5.0/kotlinx-coroutines-core-iosarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosx64/1.5.0/kotlinx-coroutines-core-iosx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-iosx64/1.5.0/kotlinx-coroutines-core-iosx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-iosx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-js/1.5.0/kotlinx-coroutines-core-js-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-js",
        "version": "1.5.0"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-js/1.5.0/kotlinx-coroutines-core-js-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-js",
        "version": "1.5.0"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-js/1.5.0/kotlinx-coroutines-core-js-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-js",
        "version": "1.5.0"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-js/1.5.0/kotlinx-coroutines-core-js-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-js",
        "version": "1.5.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-jvm/1.5.0/kotlinx-coroutines-core-jvm-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-jvm",
        "version": "1.5.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-jvm/1.5.0/kotlinx-coroutines-core-jvm-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-jvm",
        "version": "1.5.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-linuxx64/1.5.0/kotlinx-coroutines-core-linuxx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-linuxx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-macosx64/1.5.0/kotlinx-coroutines-core-macosx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-macosx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-macosx64/1.5.0/kotlinx-coroutines-core-macosx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-macosx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-mingwx64/1.5.0/kotlinx-coroutines-core-mingwx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-mingwx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "mingwX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-mingwx64/1.5.0/kotlinx-coroutines-core-mingwx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-mingwx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosarm64/1.5.0/kotlinx-coroutines-core-tvosarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosarm64/1.5.0/kotlinx-coroutines-core-tvosarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosx64/1.5.0/kotlinx-coroutines-core-tvosx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-tvosx64/1.5.0/kotlinx-coroutines-core-tvosx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-tvosx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm32/1.5.0/kotlinx-coroutines-core-watchosarm32-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm32",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm32/1.5.0/kotlinx-coroutines-core-watchosarm32-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm32",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm64/1.5.0/kotlinx-coroutines-core-watchosarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosarm64/1.5.0/kotlinx-coroutines-core-watchosarm64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosarm64",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosx64/1.5.0/kotlinx-coroutines-core-watchosx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosx64/1.5.0/kotlinx-coroutines-core-watchosx64-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosx64",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosx86/1.5.0/kotlinx-coroutines-core-watchosx86-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosx86",
        "version": "1.5.0"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-coroutines-core-watchosx86/1.5.0/kotlinx-coroutines-core-watchosx86-1.5.0.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-coroutines-core-watchosx86",
        "version": "1.5.0"
      }
    }
  ]
}
