{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "leakcanary-android",
    "version": "2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-core",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-android-2.12.aar",
          "url": "leakcanary-android-2.12.aar",
          "size": 4240,
          "sha512": "2d11f104a3e62c0656b840201817a2f98d0ca4c604a53f44296868729ad37a8dcea1ec954a3f0c9167ec8e47d7530dfe72e1133f0c31b9086112dd230f098d9b",
          "sha256": "4c4dc1dc3b339dc6b5f6a7f73d3021f6c65815a389920315dfdfa1f8ba821548",
          "sha1": "73a988391f0c8e1c8cc0011f3090624f17b89e7f",
          "md5": "597e2f6d4cc67083cef17aca8ea0213b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-android-core",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "leakcanary-object-watcher-android",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "plumber-android",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-android-2.12.aar",
          "url": "leakcanary-android-2.12.aar",
          "size": 4240,
          "sha512": "2d11f104a3e62c0656b840201817a2f98d0ca4c604a53f44296868729ad37a8dcea1ec954a3f0c9167ec8e47d7530dfe72e1133f0c31b9086112dd230f098d9b",
          "sha256": "4c4dc1dc3b339dc6b5f6a7f73d3021f6c65815a389920315dfdfa1f8ba821548",
          "sha1": "73a988391f0c8e1c8cc0011f3090624f17b89e7f",
          "md5": "597e2f6d4cc67083cef17aca8ea0213b"
        }
      ]
    }
  ]
}
