{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "shark-log",
    "version": "2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "shark-log-2.12.jar",
          "url": "shark-log-2.12.jar",
          "size": 2410,
          "sha512": "e585a1e0b5830dad52afb44fdd064f7fb7377b89841f258df3cefb27555a7d4124f2d192577f40f73da96e3a9be7e741f6fa61304cc56aeeffd6bb68a006dc75",
          "sha256": "76f62c41a43126913965f860fae6871d87a39bcd9568b8ad69febf97abc22a07",
          "sha1": "a64ea258c53f272426aad6cc878ba90e58ad003e",
          "md5": "bb6dd4e6c5810ae5d8e12a48f49ae75e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "shark-log-2.12.jar",
          "url": "shark-log-2.12.jar",
          "size": 2410,
          "sha512": "e585a1e0b5830dad52afb44fdd064f7fb7377b89841f258df3cefb27555a7d4124f2d192577f40f73da96e3a9be7e741f6fa61304cc56aeeffd6bb68a006dc75",
          "sha256": "76f62c41a43126913965f860fae6871d87a39bcd9568b8ad69febf97abc22a07",
          "sha1": "a64ea258c53f272426aad6cc878ba90e58ad003e",
          "md5": "bb6dd4e6c5810ae5d8e12a48f49ae75e"
        }
      ]
    }
  ]
}
