{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.transition",
    "module": "transition",
    "version": "1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7282859"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "transition-1.4.1.aar",
          "url": "transition-1.4.1.aar",
          "size": 181918,
          "sha512": "76b80aec89b968a7938c7d4d29d01ab278bef20970bebe83c20e020f2b9357f0b26bd3e8dfec0aa2816eeb706d434b8bcaba0b1211734d3a43d3bc3eab963cef",
          "sha256": "36d28d9ec33a8c64313842bce99c95736da5b27a6b3a513639050de82f075726",
          "sha1": "703467fbdb3d06e51d338c4a3490b54d37c92a64",
          "md5": "b3f4126bc2c5fa18e18daeb28b5e8bc9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "transition-1.4.1.aar",
          "url": "transition-1.4.1.aar",
          "size": 181918,
          "sha512": "76b80aec89b968a7938c7d4d29d01ab278bef20970bebe83c20e020f2b9357f0b26bd3e8dfec0aa2816eeb706d434b8bcaba0b1211734d3a43d3bc3eab963cef",
          "sha256": "36d28d9ec33a8c64313842bce99c95736da5b27a6b3a513639050de82f075726",
          "sha1": "703467fbdb3d06e51d338c4a3490b54d37c92a64",
          "md5": "b3f4126bc2c5fa18e18daeb28b5e8bc9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "transition-1.4.1-sources.jar",
          "url": "transition-1.4.1-sources.jar",
          "size": 132917,
          "sha512": "bbd5cbfcea8260eed2eda536e8d6138d55264addd1123a421d92bd5a74a43bc93ec1d870dcec3d367561355403cfa9ca70f2f28381ec2e2ee016c27c8a6660b1",
          "sha256": "e641fdf5c71eef8c63054e9d41052eb8a39f316797b2c436d778824fc74f07af",
          "sha1": "975f706c6c0892d0dfaa416cf04f469cfb0a4343",
          "md5": "01bd51842f407af23e39933e01034e65"
        }
      ]
    }
  ]
}
