{
  "formatVersion": "1.1",
  "component": {
    "group": "io.perfmark",
    "module": "perfmark-api",
    "version": "0.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "aukgrwir35amzdqzvtcyt63ir4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "perfmark-api-0.23.0.jar",
          "url": "perfmark-api-0.23.0.jar",
          "size": 6385,
          "sha512": "4fc516eefc912b2d40a6a7fd982cde0c24b5fbefdddbc4f37690d78e1d94762e1054390a2564638f887c3582a16a2297d5f3437aa4f28b0a588ab127345b08ca",
          "sha256": "c705b5c10c18ff3032b9e81742bc2f6b0e5607f6a6dfc0c8ad0cff75d4913042",
          "sha1": "0b813b7539fae6550541da8caafd6add86d4e22f",
          "md5": "571d67b7639e3aa95e6f2b887ca53357"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 6,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "perfmark-api-0.23.0.jar",
          "url": "perfmark-api-0.23.0.jar",
          "size": 6385,
          "sha512": "4fc516eefc912b2d40a6a7fd982cde0c24b5fbefdddbc4f37690d78e1d94762e1054390a2564638f887c3582a16a2297d5f3437aa4f28b0a588ab127345b08ca",
          "sha256": "c705b5c10c18ff3032b9e81742bc2f6b0e5607f6a6dfc0c8ad0cff75d4913042",
          "sha1": "0b813b7539fae6550541da8caafd6add86d4e22f",
          "md5": "571d67b7639e3aa95e6f2b887ca53357"
        }
      ]
    }
  ]
}
