{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "leakcanary-android-utils",
    "version": "2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-log",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-android-utils-2.12.aar",
          "url": "leakcanary-android-utils-2.12.aar",
          "size": 7677,
          "sha512": "0044af80f50fd74fadcbebf2242330bcb15f97eadb0d56acdab6721cb2c53dddd5387a225994a6e27f38582685aba24f35d7754c87a6f1c3ab36e4e92749d4d9",
          "sha256": "a7f3288ad5099b0cfdb465f87547631986611c4796f08f07c7defad89749c607",
          "sha1": "a5a738cf5fcfa3029e864b1b50fb9f5e1588dcf2",
          "md5": "47bc677cbe366a2aba624ee011bb3eac"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-log",
          "version": {
            "requires": "2.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        }
      ],
      "files": [
        {
          "name": "leakcanary-android-utils-2.12.aar",
          "url": "leakcanary-android-utils-2.12.aar",
          "size": 7677,
          "sha512": "0044af80f50fd74fadcbebf2242330bcb15f97eadb0d56acdab6721cb2c53dddd5387a225994a6e27f38582685aba24f35d7754c87a6f1c3ab36e4e92749d4d9",
          "sha256": "a7f3288ad5099b0cfdb465f87547631986611c4796f08f07c7defad89749c607",
          "sha1": "a5a738cf5fcfa3029e864b1b50fb9f5e1588dcf2",
          "md5": "47bc677cbe366a2aba624ee011bb3eac"
        }
      ]
    }
  ]
}
