{
  "formatVersion": "1.1",
  "component": {
    "url": "../../annotation/1.6.0/annotation-1.6.0.module",
    "group": "androidx.annotation",
    "module": "annotation",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-jvm-1.6.0.jar",
          "url": "annotation-jvm-1.6.0.jar",
          "size": 55218,
          "sha512": "68c4454bcfb46213caafb6b91ecce163cec0ff68e59015ab8565ebd6712f7f932bdb1aa90558b73fb6e76a75074faa030a3743a7bbd7b70b549926247d075ecf",
          "sha256": "60b10b5ef5769b79570172e015b8159405c92f034ba88b9391a977589c9deb4e",
          "sha1": "a7257339a052df0f91433cf9651231bbb802b502",
          "md5": "01c8f61d745ba9b73967a569db7a7d96"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-jvm-1.6.0.jar",
          "url": "annotation-jvm-1.6.0.jar",
          "size": 55218,
          "sha512": "68c4454bcfb46213caafb6b91ecce163cec0ff68e59015ab8565ebd6712f7f932bdb1aa90558b73fb6e76a75074faa030a3743a7bbd7b70b549926247d075ecf",
          "sha256": "60b10b5ef5769b79570172e015b8159405c92f034ba88b9391a977589c9deb4e",
          "sha1": "a7257339a052df0f91433cf9651231bbb802b502",
          "md5": "01c8f61d745ba9b73967a569db7a7d96"
        }
      ]
    }
  ]
}