{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "shark-hprof",
    "version": "2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-log",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "shark-hprof-2.12.jar",
          "url": "shark-hprof-2.12.jar",
          "size": 154586,
          "sha512": "13a3902944b45e6a62272309857316646f209957d6d6a9bb52c25428eebd8b6431328038ddd84a81fcc71eb245207f14e519640fb20944544eba0a2f73ec8c97",
          "sha256": "f8ba641c075143581eab87c3b9de9b2dc0080f8fe53cd5817b58251a617299aa",
          "sha1": "6379869f2824a437df6cdb803b88ae4984470be6",
          "md5": "1ba6fc9dc3e10582ae8d7a76f8d68137"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "shark-log",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "shark-hprof-2.12.jar",
          "url": "shark-hprof-2.12.jar",
          "size": 154586,
          "sha512": "13a3902944b45e6a62272309857316646f209957d6d6a9bb52c25428eebd8b6431328038ddd84a81fcc71eb245207f14e519640fb20944544eba0a2f73ec8c97",
          "sha256": "f8ba641c075143581eab87c3b9de9b2dc0080f8fe53cd5817b58251a617299aa",
          "sha1": "6379869f2824a437df6cdb803b88ae4984470be6",
          "md5": "1ba6fc9dc3e10582ae8d7a76f8d68137"
        }
      ]
    }
  ]
}
