{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.leakcanary",
    "module": "shark-android",
    "version": "2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.leakcanary",
          "module": "shark",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "shark-android-2.12.jar",
          "url": "shark-android-2.12.jar",
          "size": 384166,
          "sha512": "e2299f524c0f86aa6775ddb030a63b6ae1317d1495984832e6474e2fc862ecae2f8a6370399e8d8cdef5e42737b652f028f699d1e2d8b41241e6247e10ed94f8",
          "sha256": "4cc04a4ed1815b0060766e2363518732f20bcc88f24b2aa27578274137e6ad77",
          "sha1": "57e1c0de550aaf316462385e020f92600a9f2981",
          "md5": "a399c74cbe856dd00e8cb387923f100c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.72"
          }
        },
        {
          "group": "com.squareup.leakcanary",
          "module": "shark",
          "version": {
            "requires": "2.12"
          }
        }
      ],
      "files": [
        {
          "name": "shark-android-2.12.jar",
          "url": "shark-android-2.12.jar",
          "size": 384166,
          "sha512": "e2299f524c0f86aa6775ddb030a63b6ae1317d1495984832e6474e2fc862ecae2f8a6370399e8d8cdef5e42737b652f028f699d1e2d8b41241e6247e10ed94f8",
          "sha256": "4cc04a4ed1815b0060766e2363518732f20bcc88f24b2aa27578274137e6ad77",
          "sha1": "57e1c0de550aaf316462385e020f92600a9f2981",
          "md5": "a399c74cbe856dd00e8cb387923f100c"
        }
      ]
    }
  ]
}
