{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6915737"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tracing-1.0.0.aar",
          "url": "tracing-1.0.0.aar",
          "size": 4444,
          "sha512": "d154f32553d2cae7d7e5b33a85e81c4c851dee461c900d1fac8277ef4becd047b2d08bec790759ba333f26be4b7a3de9ebfbc7521642cc2b1d539516eb347b4f",
          "sha256": "07b8b6139665b884a162eccf97891ca50f7f56831233bf25168ae04f7b568612",
          "sha1": "69cef34711dffbc517e7a0a419ec4a98f84f496a",
          "md5": "8081a5dae7393cade5e6801814292665"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-1.0.0.aar",
          "url": "tracing-1.0.0.aar",
          "size": 4444,
          "sha512": "d154f32553d2cae7d7e5b33a85e81c4c851dee461c900d1fac8277ef4becd047b2d08bec790759ba333f26be4b7a3de9ebfbc7521642cc2b1d539516eb347b4f",
          "sha256": "07b8b6139665b884a162eccf97891ca50f7f56831233bf25168ae04f7b568612",
          "sha1": "69cef34711dffbc517e7a0a419ec4a98f84f496a",
          "md5": "8081a5dae7393cade5e6801814292665"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tracing-1.0.0-sources.jar",
          "url": "tracing-1.0.0-sources.jar",
          "size": 5581,
          "sha512": "38637c78f62d2591f6f965df88a5a3b5eeddf079ec82020eabf8baae1af0e706828ab81d8a368a2ff8d77744e73b010d0297c4e70da530f3ecf456d6664032c7",
          "sha256": "a593c115d145df9cb9ae2226960da1d53ff8590eff1c285e7c9de2b6727d3c21",
          "sha1": "aa6dafdce323d80a993c5427cf81d5072f023c8c",
          "md5": "a54304b44519d7d24390d3d6f34918ba"
        }
      ]
    }
  ]
}
